# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Wuttinan Kachayoot
tagline:          words and thoughts
url:              http://wuttinan.com
paginate:         1
baseurl:          /
author:
  name:           Wuttinan Kachyoot
  url:            https://twitter.com/wuttinan
  email:          wuttinan@me.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wuttinan/wuttinan.github.io

# Page Lists Config
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# More Features 
gems:
  - jekyll-redirect-from # Allow URL Redirects
  - jemoji #Enable Emoji
