# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Wuttinan Kachayoot
tagline:          words and thoughts
url:              http://wuttinan.com
paginate:         1
baseurl:          /
author:
  name:           Wuttinan Kachyoot
  url:            https://wuttinan.com
  email:          wuttinan@me.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wuttinan/wuttinan.github.io
